name: Publish release artifacts

on: [ push, workflow_dispatch ]

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: [ "10.3.3" ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}
      - uses: eskatos/gradle-command-action@v2
        with:
          gradle-version: 7.5
          arguments: -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
      - uses: actions/upload-artifact@v3
        with:
          name: Ghidra-Switch-Loader_${{ matrix.ghidra }}
          path: dist/*.zip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.zip"
          tag: ${{ github.sha }}
          allowUpdates: true
          artifactErrorsFailBuild: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
