name: Publish release artifacts

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release git tag
        type: string
        required: true
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: [ "11.3.2" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Ghidra ${{ matrix.ghidra }}
        uses: antoniovazquezblanco/setup-ghidra@v2.0.14
        with:
          version: ${{ matrix.ghidra }}

      - name: Build extension
        run: ./gradlew

      - uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/SwitchLoader-*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/SwitchLoader-*.zip
          tag: ${{ inputs.tag }}
          overwrite: true
          file_glob: true
